name = "PiecewiseTools"
uuid = "26dc6a34-ad44-11e8-07b6-8b7dc6cbd4f9"
authors = ["TravisBarryDick <travis.barry.dick@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
